Added metadata to publish channels_rpc
quantivly/channels-rpc pull request #1
Opened 2024-12-12 10:03 UTC by VishnuSubramanianTrenser

2024-12-16 14:11 UTC, zvi-quantivly requested changes

2024-12-16 14:11 UTC, zvi-quantivly commented on pyproject.toml
> +requires = ["poetry-core", "setuptools>=42", "wheel"]
There shouldn't be a need for this. Poetry handles packaging and building.

2024-12-16 14:11 UTC, zvi-quantivly commented on pyproject.toml
> +[project]
There's some duplication between the `[project]` section and the `[tool.poertry]`. IIUC, `[project]` is newer and more compliant with the latest Python packaging best practices, but not 100%. In any case, let's remove the duplication in metadata.

2024-12-16 14:11 UTC, zvi-quantivly commented on setup.cfg
_setup.cfg_ is deprecated and should not be needed.

2024-12-16 14:11 UTC, zvi-quantivly commented on scripts/publish.sh
> +
```suggestion

python -m pip install --upgrade build twine

```

2024-12-16 14:11 UTC, zvi-quantivly commented on scripts/publish.sh
Are we also uploading to [Test PyPI](https://test.pypi.org/)? We generally should publish to Test PyPI before we do to PyPI, so it might be good to support a flag for that.

2024-12-19 05:09 UTC, VishnuSubramanianTrenser commented on scripts/publish.sh
Published on test PyPl : https://test.pypi.org/project/channels-rpc/0.1.1/

2024-12-19 06:51 UTC, zvi-quantivly approved these changes

2024-12-26 05:16 UTC, merged